### ISSUE TITLE
Arithmetics error: precedence of '+' over '-'

### ISSUE THREAD

**Issue by Solovyev-Pavel** [rezzza/exprlib#6]
While using the parser I ran into the following error: it seems that the parser always applies addition (+) before subtraction (-) when there are no brackets to clarify the order of operations.

    $expr = '1 - 2 + 3'; // = 2
    $result = \exprlib\Parser::build($expr)->evaluate();
    var_dump($result); // $result = -4

    $expr = '1 - 2 + 3 + 4'; // = 6
    $result = \exprlib\Parser::build($expr)->evaluate();
    var_dump($result); // $result = -8

    $expr = '(1 - 2 + 3) + 4'; // = 6
    $result = \exprlib\Parser::build($expr)->evaluate();
    var_dump($result); // $result = 0

Meanwhile

    $expr = '(1 - 2) + 3'; // = 2
    $result = \exprlib\Parser::build($expr)->evaluate();
    var_dump($result); // $result = 2 as it should be

    $expr = '(1 - 2) + 3 + 4'; // = 6
    $result = \exprlib\Parser::build($expr)->evaluate();
    var_dump($result); // $result = 6 as it should be

**Comment by stephpy** [comment]
Hi,

As it's said in README, You should look at [Hoa\Math](https://github.com/hoaproject/Math), this library is no more maintained and there is few issues.

Hoa\Math is just ... awesome. :)
